CONFIG_ZMK_KEYBOARD_NAME="sg4"
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=35
CONFIG_BT_MAX_CONN=9
CONFIG_BT_MAX_PAIRED=9

CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# CONFIG_ZMK_SLEEP=y
